CREATE PROCEDURE [data].[Populate_dbo_DimChannel]
AS
BEGIN
/*
	Table's data:    [dbo].[DimChannel]
	Data Source:     [KNMSI10\SQL2016].[ContosoRetailDW]
	Created on:      14/05/2018 10:45:17
	Scripted by:     MicrosoftAccount\kamil@nowinski.net
	Generated by     Data Script Writer - ver. 2.0.0.0
*/
PRINT 'Populating data into [dbo].[DimChannel]';

IF OBJECT_ID('tempdb.dbo.#dbo_DimChannel') IS NOT NULL DROP TABLE #dbo_DimChannel;
SELECT * INTO #dbo_DimChannel FROM [dbo].[DimChannel] WHERE 0=1;

SET IDENTITY_INSERT #dbo_DimChannel ON;

INSERT INTO #dbo_DimChannel 
 ([ChannelKey], [ChannelLabel], [ChannelName], [ChannelDescription], [ETLLoadID], [LoadDate], [UpdateDate])
SELECT CAST([ChannelKey] AS int) AS [ChannelKey], [ChannelLabel], [ChannelName], [ChannelDescription], [ETLLoadID], [LoadDate], [UpdateDate] FROM 
(VALUES
	  (1,	'01',	'Store',	'Store',	1,	'20090711 14:43:19.000',	'20090711 14:43:19.000')
	, (2,	'02',	'Online',	'Online',	1,	'20090711 14:43:19.000',	'20090711 14:43:19.000')
	, (3,	'03',	'Catalog',	'Catalog',	1,	'20090711 14:43:19.000',	'20090711 14:43:19.000')
	, (4,	'04',	'Reseller',	'Reseller',	1,	'20090711 14:43:19.000',	'20090711 14:43:19.000')
) as v ([ChannelKey], [ChannelLabel], [ChannelName], [ChannelDescription], [ETLLoadID], [LoadDate], [UpdateDate]);


SET IDENTITY_INSERT #dbo_DimChannel OFF;

SET IDENTITY_INSERT [dbo].[DimChannel] ON;


WITH cte_data as (SELECT CAST([ChannelKey] AS int) AS [ChannelKey], [ChannelLabel], [ChannelName], [ChannelDescription], [ETLLoadID], [LoadDate], [UpdateDate] FROM [#dbo_DimChannel])
MERGE [dbo].[DimChannel] as t
USING cte_data as s
	ON t.[ChannelKey] = s.[ChannelKey]
WHEN NOT MATCHED BY target THEN
	INSERT ([ChannelKey], [ChannelLabel], [ChannelName], [ChannelDescription], [ETLLoadID], [LoadDate], [UpdateDate])
	VALUES (s.[ChannelKey], s.[ChannelLabel], s.[ChannelName], s.[ChannelDescription], s.[ETLLoadID], s.[LoadDate], s.[UpdateDate])
WHEN MATCHED THEN 
	UPDATE SET 
	[ChannelLabel] = s.[ChannelLabel], [ChannelName] = s.[ChannelName], [ChannelDescription] = s.[ChannelDescription], [ETLLoadID] = s.[ETLLoadID], [LoadDate] = s.[LoadDate], [UpdateDate] = s.[UpdateDate]
WHEN NOT MATCHED BY source THEN
	DELETE
;

SET IDENTITY_INSERT [dbo].[DimChannel] OFF;

DROP TABLE #dbo_DimChannel;

-- End data of table: [dbo].[DimChannel] --
END
GO
